# Dockerfile
FROM postgres:16

# Instale as dependências necessárias
RUN apt-get update && \
    apt-get install -y \
        postgresql-16-pgrouting \
        postgis

# Continuação do Dockerfile (restante das instruções)
